### ISSUE TITLE
PSROI Align 模块

### ISSUE THREAD

**Issue by curryforthree** [ouyanghuiyu/Thundernet_Pytorch#7]
你好，非常感谢你的工作，我在build psroialign模块之后跑不通，提示cudaCheckError() failed : invalid device function，在setup.py中新增了"nvcc":['-arch=sm_61']，但还是没有解决，请问你有遇到这样的情况吗？

**Comment by ouyanghuiyu** [comment]
你好，你用的torch是什么版本的，还是cuda版本的原因？

**Comment by curryforthree** [comment]
> 你好，你用的torch是什么版本的，还是cuda版本的原因？

我的版本是pytorch1.3.1   cudatoolkit 10.1.243

**Comment by ouyanghuiyu** [comment]
我是1.2.0 cuda 10.1 应该没问题的呀

**Comment by curryforthree** [comment]
> 我是1.2.0 cuda 10.1 应该没问题的呀

开了个干净的虚拟环境，保持版本一致pytorch 1.2.0、torchvision 0.4，问题解决了，多谢~

**Comment by yyf7329081** [comment]
您好，我机器安装的cuda9.0，在conda虚拟环境中安装了pytorch1.2.0，自动安装了cudatoolkit10.0.130。
在编译生成的文件中只有文件夹"cpu"，缺少"cuda"，是因为编译必须用cuda10.1，无法使用cuda9.0吗？我需要再装个cuda10.1吗?
